####################################
##      Satori Configuration      ##
## uncomment to override defaults ##
####################################

## a local python flask server provides the user interface
## and the port it runs on can be configured here: (1024–49151)
user interface port: 24601

## a local nodejs server provides the engine with access
## to data streams and the port it runs on can be configured here: (1024–49151)
streamr light client port: 24686

## Satori saves data streams in the form of parquet files here:
# absolute data path: /satori/data

## Satori saves models in the form of joblib files here:
# absolute model path: /satori/model

## Satori saves wallet information:
# absolute wallet path: /satori/wallet

## the system Satori uses to get its streams:
# default source of data streams: streamr

## Satori connects to an electrumX server to get wallet balances
## to reduce the load on any one server multiple servers can be
## specified and a random one will be chosen on startup:
#electrumx servers: 
#  - rvn4lyfe.com:50002
#  - moontree.com:50002